name: BlazinVanish
author: iiFlamiinBlaze
version: 1.0.1
api: 3.0.0-ALPHA12
main: iiFlamiinBlaze\BlazinVanish\BlazinVanish
website: https://github.com/iiFlamiinBlaze/BlazinVanish
commands:
 vanish:
  permission: vanish.command
  description: "Use this command to vanish"
permissions:
 vanish.command:
  default: op